version: '2'
services:
    testreact-app:
        image: testreact
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://testreact-postgresql:5432/testreact
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    testreact-postgresql:
        extends:
            file: postgresql.yml
            service: testreact-postgresql
